export const Order = {
  id: 0,
  orderCode: "",
  customer: {
    id: 0,
    name: "",
    email: "",
    phone: "",
  },
  paymentType: 0,
  deliveryPhone: "",
  checkInDate: "",
  totalAmount: 0,
  discountRate: 0,
  finalAmount: 0,
  shippingFee: 0,
  orderStatus: 0,
  isConfirm: false,
  quantity: 0,
  note: "nothing",
  orderDetails: [
    {
      id: 0,
      orderId: 0,
      productCode: "",
      productName: "",
      unitPrice: 0,
      quantity: 0,
      totalAmount: 0,
      discountRate: 0,
      finalAmount: 0,
      note: "nothing",
    },
  ],
};
