export const Product = {
  id: 0,
  name: "",
  productCode: "",
  price: 0,
  description: "",
  execptedReleaseDate: "",
  isActive: true,
  category: {
    id: 0,
    name: "",
    isActive: true,
    createAt: "",
    updateAt: "",
  },
  campain: {
    id: 0,
    name: "",
    isActive: true,
    campainPhases: [],
  },
  discountRate: 0,
  productDetails: [
    {
      id: 0,
      productId: 0,
      size: "",
      color: "",
      imgUrl: "",
      width: 0,
      height: 0,
      material: "",
      description: "",
      updateAt: "",
    },
  ],
};

export const ProductUpdate = {
  name: "",
  productCode: "",
  price: 0,
  description: "",
  execptedReleaseDate: "",
  isActive: true,
  categoryId: 0,
  campainId: null,
  discountRate: 0,
  productDetails: [
    {
      size: "",
      color: "",
      imgUrl: "",
      width: 0,
      height: 0,
      material: "",
      description: "",
    },
  ],
};
