export const userInputs = [
  {
    id: 1,
    label: "Username",
    type: "text",
    placeholder: "john_doe",
  },
  {
    id: 2,
    label: "Name and surname",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: 3,
    label: "Email",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: 4,
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
  },
  {
    id: 5,
    label: "Password",
    type: "password",
  },
  {
    id: 6,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    id: 7,
    label: "Country",
    type: "text",
    placeholder: "USA",
  },
];

export const productInputs = [
  {
    id: 1,
    label: "Name",
    key: "name",
    type: "text",
    placeholder: "Apple Macbook Pro",
    // value: "Loa",
  },
  {
    id: 2,
    label: "Code",
    key: "productCode",
    type: "text",
    placeholder: "Description",
    // value: "LOA999",
  },
  {
    id: 3,
    label: "Expected Release Date",
    key: "execptedReleaseDate",
    type: "date",
    placeholder: "Computers",
    // value: "2023-12-03",
  },
  {
    id: 4,
    label: "Price (VND)",
    key: "price",
    type: "number",
    placeholder: "100",
    // value: 120000,
  },
  {
    id: 5,
    label: "Discount Rate (%)",
    key: "discountRate",
    type: "number",
    placeholder: "30",
    // value: 30,
  },
  {
    id: 6,
    label: "Description",
    key: "description",
    type: "text",
    placeholder: "in stock",
  },
  {
    id: "productDetails.size",
    label: "Size",
    key: "productDetails.size",
    type: "number",
    placeholder: "43",
    // value: 40,
  },
  {
    id: "productDetails.color",
    label: "Color",
    key: "productDetails.color",
    type: "text",
    placeholder: "white",
    // value: "white",
  },
  {
    id: "productDetails.width",
    label: "Width",
    key: "productDetails.width",
    type: "number",
    placeholder: "120",
    // value: 120,
  },
  {
    id: "productDetails.height",
    label: "Height",
    key: "productDetails.height",
    type: "number",
    placeholder: "120",
    // value: 40,
  },
  {
    id: "productDetails.material",
    label: "Material",
    key: "productDetails.material",
    type: "text",
    placeholder: "leather",
    // value: "leather",
  },
];
